package Year2022.day05;

import java.util.ArrayList;

import tools.RunPuzzle;
import tools.TestCase;

public class SupplyStacks extends RunPuzzle {

	public SupplyStacks(int dayNumber, String dayTitle, Object puzzleInput) {
		super(dayNumber, dayTitle, puzzleInput);
	}

	@Override
	public ArrayList<TestCase> createTestCases() {
		ArrayList<TestCase> tests = new ArrayList<TestCase>();
		tests.add(new TestCase<CraneInput, String>(1, new CraneInput(test1Stacks, test1Instructions), "CMZ"));
		tests.add(new TestCase<CraneInput, String>(2, new CraneInput(test1Stacks, test1Instructions), "MCD"));
		return tests;
	}

	@Override
	public void printResult(Object result) {
		System.out.println(this.defaultResultIndent + (String)result);
	}

	@Override
	public Object doProcessing(int section, Object input) {
		ArrayList<StringBuilder> stacks = new ArrayList<StringBuilder>();
		ArrayList<Instruction> instructions = new ArrayList<Instruction>();
		CraneInput setup = (CraneInput)input;
		
		for (String s : setup.stacks) {
			stacks.add(new StringBuilder(s));
		}
		for (String s : setup.instructions) {
			instructions.add(new Instruction(s));
		}
		
		for (Instruction i : instructions) {
			if (section == 1) {
				for (int j = 0; j < i.numberToMove; j++) {
					stacks.get(i.targetStack - 1).insert(0, stacks.get(i.sourceStack - 1).charAt(0));
					stacks.get(i.sourceStack - 1).deleteCharAt(0);
				}
			}
			else {
				stacks.get(i.targetStack - 1).insert(0, stacks.get(i.sourceStack - 1).substring(0, i.numberToMove));
				stacks.set(i.sourceStack - 1, new StringBuilder(stacks.get(i.sourceStack - 1).substring(i.numberToMove)));
			}
		}
		
		StringBuilder result = new StringBuilder();
		for (StringBuilder stack : stacks) {
			result.append(stack.charAt(0));
		}
		return result.toString();
	}

	public static void main(String[] args) {
		RunPuzzle puzzle = new SupplyStacks(5, "Supply Stacks", new CraneInput(puzzleStacks, puzzleInstructions));
		puzzle.run();
	}
	
	public static class Instruction {
		int numberToMove;
		int sourceStack;
		int targetStack;
		
		public Instruction(String s) {
			parseInstruction(s);
		}
		
		// "move # from # to #"
		public void parseInstruction(String s) {
			s = s.trim();
			
			int startIndex = s.indexOf(" ");
			int endIndex = s.indexOf(" ", startIndex + 1);
			numberToMove = Integer.parseInt(s.substring(startIndex + 1, endIndex));
			
			startIndex = s.indexOf(" ", endIndex + 1);
			endIndex = s.indexOf(" ", startIndex + 1);
			sourceStack = Integer.parseInt(s.substring(startIndex + 1, endIndex));
			
			startIndex = s.indexOf(" ", endIndex + 1);
			targetStack = Integer.parseInt(s.substring(startIndex + 1));
		}
	}

	public static class CraneInput {
		String[] stacks;
		String[] instructions;
		public CraneInput(String[] stacks, String[] instructions) {
			this.stacks = stacks;
			this.instructions = instructions;
		}
	}
	// Stacks of crates are listed TOP -> BOTTOM
	static String[] test1Stacks = {
			"NZ",
			"DCM",
			"P"
	};
	static String[] test1Instructions = {
			"move 1 from 2 to 1",
			"move 3 from 1 to 3",
			"move 2 from 2 to 1",
			"move 1 from 1 to 2"
	};
	
	static String[] puzzleStacks = {
			"QFLSR",
			"TPGQZN",
			"BQMS",
			"QBCHJZGT",
			"SFNBMHP",
			"GVLSNQCP",
			"FCW",
			"MPVWZGHQ",
			"RNCLDZG"
	};
	static String[] puzzleInstructions = {
			"move 1 from 2 to 6       ",
			"move 3 from 7 to 9       ",
			"move 7 from 9 to 4       ",
			"move 2 from 5 to 3       ",
			"move 3 from 2 to 8       ",
			"move 14 from 4 to 5      ",
			"move 1 from 2 to 1       ",
			"move 1 from 2 to 3       ",
			"move 3 from 6 to 8       ",
			"move 3 from 6 to 9       ",
			"move 1 from 4 to 6       ",
			"move 5 from 9 to 8       ",
			"move 9 from 8 to 9       ",
			"move 3 from 3 to 8       ",
			"move 8 from 9 to 4       ",
			"move 2 from 1 to 7       ",
			"move 4 from 1 to 5       ",
			"move 2 from 7 to 1       ",
			"move 1 from 9 to 6       ",
			"move 7 from 4 to 7       ",
			"move 1 from 8 to 4       ",
			"move 1 from 9 to 8       ",
			"move 2 from 6 to 7       ",
			"move 7 from 7 to 3       ",
			"move 10 from 3 to 1      ",
			"move 1 from 3 to 2       ",
			"move 1 from 2 to 9       ",
			"move 1 from 9 to 8       ",
			"move 15 from 5 to 8      ",
			"move 1 from 6 to 9       ",
			"move 2 from 7 to 3       ",
			"move 11 from 1 to 8      ",
			"move 1 from 9 to 8       ",
			"move 1 from 1 to 5       ",
			"move 3 from 5 to 2       ",
			"move 2 from 6 to 9       ",
			"move 1 from 2 to 4       ",
			"move 2 from 4 to 5       ",
			"move 1 from 3 to 6       ",
			"move 5 from 8 to 3       ",
			"move 12 from 8 to 4      ",
			"move 2 from 2 to 5       ",
			"move 12 from 8 to 1      ",
			"move 1 from 6 to 9       ",
			"move 10 from 5 to 7      ",
			"move 3 from 3 to 9       ",
			"move 6 from 8 to 9       ",
			"move 2 from 3 to 5       ",
			"move 8 from 4 to 7       ",
			"move 1 from 3 to 2       ",
			"move 6 from 8 to 6       ",
			"move 8 from 9 to 3       ",
			"move 2 from 5 to 4       ",
			"move 1 from 2 to 3       ",
			"move 2 from 9 to 2       ",
			"move 1 from 9 to 2       ",
			"move 1 from 2 to 1       ",
			"move 2 from 2 to 4       ",
			"move 5 from 4 to 2       ",
			"move 3 from 2 to 3       ",
			"move 2 from 4 to 2       ",
			"move 18 from 7 to 3      ",
			"move 3 from 6 to 9       ",
			"move 1 from 6 to 3       ",
			"move 1 from 4 to 1       ",
			"move 1 from 6 to 3       ",
			"move 6 from 3 to 9       ",
			"move 2 from 2 to 6       ",
			"move 26 from 3 to 7      ",
			"move 2 from 2 to 3       ",
			"move 2 from 6 to 8       ",
			"move 3 from 1 to 5       ",
			"move 8 from 9 to 1       ",
			"move 1 from 8 to 5       ",
			"move 1 from 3 to 1       ",
			"move 2 from 9 to 3       ",
			"move 1 from 1 to 2       ",
			"move 12 from 1 to 7      ",
			"move 1 from 8 to 5       ",
			"move 2 from 3 to 5       ",
			"move 1 from 3 to 6       ",
			"move 2 from 6 to 2       ",
			"move 7 from 5 to 7       ",
			"move 1 from 4 to 2       ",
			"move 15 from 7 to 4      ",
			"move 1 from 4 to 9       ",
			"move 1 from 7 to 6       ",
			"move 14 from 4 to 2      ",
			"move 1 from 1 to 2       ",
			"move 5 from 1 to 5       ",
			"move 4 from 5 to 4       ",
			"move 1 from 6 to 3       ",
			"move 4 from 4 to 7       ",
			"move 1 from 9 to 2       ",
			"move 1 from 3 to 5       ",
			"move 2 from 5 to 1       ",
			"move 1 from 1 to 6       ",
			"move 2 from 1 to 5       ",
			"move 9 from 2 to 9       ",
			"move 1 from 6 to 1       ",
			"move 1 from 1 to 9       ",
			"move 1 from 5 to 4       ",
			"move 1 from 5 to 6       ",
			"move 4 from 7 to 2       ",
			"move 1 from 4 to 1       ",
			"move 18 from 7 to 1      ",
			"move 17 from 1 to 7      ",
			"move 4 from 9 to 5       ",
			"move 1 from 5 to 8       ",
			"move 1 from 1 to 4       ",
			"move 2 from 9 to 6       ",
			"move 3 from 9 to 7       ",
			"move 1 from 1 to 5       ",
			"move 1 from 7 to 5       ",
			"move 16 from 7 to 2      ",
			"move 1 from 4 to 2       ",
			"move 1 from 8 to 7       ",
			"move 1 from 9 to 8       ",
			"move 1 from 8 to 4       ",
			"move 3 from 5 to 3       ",
			"move 15 from 7 to 6      ",
			"move 7 from 6 to 4       ",
			"move 9 from 6 to 2       ",
			"move 2 from 5 to 7       ",
			"move 2 from 6 to 8       ",
			"move 4 from 4 to 7       ",
			"move 2 from 8 to 1       ",
			"move 11 from 2 to 7      ",
			"move 1 from 4 to 2       ",
			"move 2 from 3 to 6       ",
			"move 3 from 4 to 5       ",
			"move 12 from 7 to 1      ",
			"move 1 from 7 to 3       ",
			"move 31 from 2 to 4      ",
			"move 3 from 7 to 2       ",
			"move 1 from 6 to 3       ",
			"move 1 from 5 to 1       ",
			"move 1 from 5 to 2       ",
			"move 2 from 3 to 4       ",
			"move 1 from 6 to 1       ",
			"move 1 from 3 to 6       ",
			"move 1 from 5 to 6       ",
			"move 1 from 2 to 4       ",
			"move 11 from 1 to 4      ",
			"move 5 from 1 to 5       ",
			"move 1 from 7 to 3       ",
			"move 3 from 5 to 8       ",
			"move 1 from 8 to 7       ",
			"move 1 from 5 to 3       ",
			"move 2 from 8 to 5       ",
			"move 2 from 6 to 2       ",
			"move 2 from 5 to 1       ",
			"move 1 from 7 to 9       ",
			"move 1 from 3 to 9       ",
			"move 2 from 9 to 5       ",
			"move 1 from 1 to 6       ",
			"move 1 from 6 to 5       ",
			"move 1 from 3 to 5       ",
			"move 13 from 4 to 8      ",
			"move 5 from 2 to 3       ",
			"move 3 from 3 to 4       ",
			"move 1 from 8 to 6       ",
			"move 4 from 5 to 2       ",
			"move 1 from 1 to 5       ",
			"move 1 from 3 to 7       ",
			"move 2 from 5 to 4       ",
			"move 11 from 4 to 5      ",
			"move 1 from 3 to 7       ",
			"move 15 from 4 to 2      ",
			"move 1 from 6 to 4       ",
			"move 19 from 2 to 8      ",
			"move 8 from 8 to 3       ",
			"move 2 from 3 to 8       ",
			"move 7 from 5 to 4       ",
			"move 6 from 3 to 4       ",
			"move 8 from 4 to 5       ",
			"move 7 from 4 to 6       ",
			"move 2 from 7 to 5       ",
			"move 9 from 5 to 6       ",
			"move 13 from 8 to 3      ",
			"move 3 from 4 to 3       ",
			"move 6 from 3 to 4       ",
			"move 6 from 8 to 2       ",
			"move 4 from 5 to 9       ",
			"move 5 from 8 to 7       ",
			"move 4 from 6 to 2       ",
			"move 5 from 3 to 5       ",
			"move 1 from 6 to 9       ",
			"move 8 from 2 to 6       ",
			"move 1 from 8 to 7       ",
			"move 1 from 2 to 5       ",
			"move 1 from 4 to 1       ",
			"move 3 from 3 to 1       ",
			"move 1 from 7 to 3       ",
			"move 4 from 9 to 8       ",
			"move 6 from 6 to 2       ",
			"move 2 from 8 to 4       ",
			"move 1 from 7 to 6       ",
			"move 3 from 5 to 1       ",
			"move 4 from 5 to 3       ",
			"move 6 from 2 to 9       ",
			"move 4 from 7 to 4       ",
			"move 2 from 8 to 5       ",
			"move 2 from 9 to 5       ",
			"move 4 from 5 to 6       ",
			"move 1 from 2 to 5       ",
			"move 8 from 6 to 7       ",
			"move 18 from 4 to 2      ",
			"move 2 from 3 to 6       ",
			"move 6 from 1 to 8       ",
			"move 8 from 7 to 9       ",
			"move 9 from 6 to 4       ",
			"move 1 from 5 to 4       ",
			"move 5 from 8 to 4       ",
			"move 1 from 4 to 5       ",
			"move 1 from 8 to 1       ",
			"move 8 from 9 to 8       ",
			"move 3 from 3 to 9       ",
			"move 5 from 2 to 7       ",
			"move 1 from 5 to 2       ",
			"move 2 from 4 to 8       ",
			"move 11 from 2 to 8      ",
			"move 1 from 7 to 2       ",
			"move 2 from 6 to 5       ",
			"move 1 from 6 to 2       ",
			"move 4 from 2 to 3       ",
			"move 2 from 1 to 3       ",
			"move 5 from 9 to 7       ",
			"move 1 from 5 to 8       ",
			"move 6 from 7 to 8       ",
			"move 7 from 3 to 7       ",
			"move 1 from 5 to 9       ",
			"move 3 from 9 to 7       ",
			"move 1 from 4 to 1       ",
			"move 1 from 9 to 8       ",
			"move 8 from 7 to 3       ",
			"move 1 from 2 to 4       ",
			"move 1 from 1 to 7       ",
			"move 9 from 3 to 7       ",
			"move 7 from 4 to 7       ",
			"move 8 from 7 to 3       ",
			"move 1 from 7 to 9       ",
			"move 13 from 7 to 4      ",
			"move 1 from 4 to 6       ",
			"move 11 from 8 to 2      ",
			"move 5 from 3 to 7       ",
			"move 1 from 9 to 6       ",
			"move 7 from 2 to 9       ",
			"move 2 from 2 to 4       ",
			"move 4 from 9 to 2       ",
			"move 17 from 8 to 3      ",
			"move 3 from 3 to 4       ",
			"move 1 from 7 to 6       ",
			"move 5 from 2 to 3       ",
			"move 8 from 4 to 1       ",
			"move 2 from 6 to 4       ",
			"move 1 from 2 to 7       ",
			"move 1 from 1 to 4       ",
			"move 1 from 8 to 2       ",
			"move 2 from 7 to 4       ",
			"move 7 from 1 to 9       ",
			"move 16 from 4 to 2      ",
			"move 1 from 6 to 1       ",
			"move 2 from 2 to 9       ",
			"move 6 from 2 to 7       ",
			"move 1 from 1 to 6       ",
			"move 3 from 2 to 6       ",
			"move 10 from 3 to 6      ",
			"move 6 from 9 to 8       ",
			"move 3 from 4 to 3       ",
			"move 6 from 9 to 2       ",
			"move 4 from 3 to 7       ",
			"move 10 from 2 to 5      ",
			"move 2 from 2 to 6       ",
			"move 3 from 6 to 3       ",
			"move 1 from 8 to 2       ",
			"move 1 from 2 to 6       ",
			"move 5 from 6 to 1       ",
			"move 3 from 6 to 7       ",
			"move 5 from 8 to 4       ",
			"move 3 from 7 to 1       ",
			"move 2 from 6 to 1       ",
			"move 2 from 4 to 1       ",
			"move 2 from 5 to 8       ",
			"move 1 from 8 to 7       ",
			"move 1 from 8 to 9       ",
			"move 8 from 3 to 4       ",
			"move 11 from 1 to 7      ",
			"move 1 from 9 to 8       ",
			"move 1 from 8 to 3       ",
			"move 3 from 6 to 3       ",
			"move 1 from 6 to 8       ",
			"move 3 from 5 to 2       ",
			"move 1 from 8 to 6       ",
			"move 2 from 5 to 8       ",
			"move 3 from 5 to 6       ",
			"move 3 from 2 to 4       ",
			"move 2 from 8 to 4       ",
			"move 22 from 7 to 3      ",
			"move 12 from 3 to 2      ",
			"move 9 from 3 to 9       ",
			"move 1 from 1 to 2       ",
			"move 2 from 6 to 8       ",
			"move 2 from 8 to 4       ",
			"move 2 from 6 to 5       ",
			"move 11 from 3 to 1      ",
			"move 18 from 4 to 3      ",
			"move 3 from 7 to 3       ",
			"move 1 from 5 to 7       ",
			"move 3 from 2 to 4       ",
			"move 2 from 4 to 9       ",
			"move 6 from 1 to 4       ",
			"move 1 from 5 to 1       ",
			"move 10 from 9 to 3      ",
			"move 27 from 3 to 9      ",
			"move 6 from 2 to 8       ",
			"move 5 from 4 to 2       ",
			"move 3 from 3 to 8       ",
			"move 1 from 7 to 8       ",
			"move 10 from 8 to 2      ",
			"move 5 from 1 to 5       ",
			"move 1 from 3 to 5       ",
			"move 1 from 1 to 8       ",
			"move 14 from 9 to 4      ",
			"move 6 from 5 to 6       ",
			"move 11 from 9 to 4      ",
			"move 6 from 6 to 3       ",
			"move 1 from 8 to 6       ",
			"move 2 from 9 to 5       ",
			"move 1 from 2 to 5       ",
			"move 8 from 2 to 1       ",
			"move 12 from 4 to 7      ",
			"move 1 from 6 to 8       ",
			"move 14 from 4 to 1      ",
			"move 1 from 9 to 8       ",
			"move 1 from 5 to 1       ",
			"move 2 from 5 to 2       ",
			"move 11 from 1 to 6      ",
			"move 11 from 6 to 1      ",
			"move 1 from 8 to 7       ",
			"move 1 from 8 to 2       ",
			"move 12 from 1 to 7      ",
			"move 1 from 4 to 7       ",
			"move 5 from 1 to 5       ",
			"move 5 from 2 to 6       ",
			"move 1 from 5 to 6       ",
			"move 1 from 2 to 9       ",
			"move 6 from 1 to 3       ",
			"move 19 from 7 to 2      ",
			"move 1 from 9 to 6       ",
			"move 9 from 3 to 2       ",
			"move 9 from 2 to 7       ",
			"move 3 from 5 to 8       ",
			"move 1 from 5 to 1       ",
			"move 3 from 3 to 9       ",
			"move 7 from 2 to 9       ",
			"move 15 from 7 to 2      ",
			"move 10 from 9 to 4      ",
			"move 4 from 4 to 9       ",
			"move 1 from 6 to 4       ",
			"move 1 from 1 to 6       ",
			"move 26 from 2 to 5      ",
			"move 1 from 7 to 3       ",
			"move 6 from 4 to 8       ",
			"move 3 from 2 to 9       ",
			"move 6 from 8 to 3       ",
			"move 4 from 5 to 7       ",
			"move 1 from 4 to 5       ",
			"move 2 from 2 to 1       ",
			"move 6 from 9 to 1       ",
			"move 3 from 3 to 8       ",
			"move 3 from 2 to 8       ",
			"move 3 from 7 to 9       ",
			"move 6 from 1 to 7       ",
			"move 2 from 3 to 2       ",
			"move 2 from 2 to 5       ",
			"move 1 from 8 to 6       ",
			"move 4 from 7 to 3       ",
			"move 10 from 5 to 3      ",
			"move 4 from 9 to 1       ",
			"move 6 from 3 to 1       ",
			"move 1 from 7 to 4       ",
			"move 4 from 3 to 2       ",
			"move 1 from 3 to 1       ",
			"move 13 from 1 to 5      ",
			"move 1 from 3 to 7       ",
			"move 1 from 3 to 8       ",
			"move 4 from 6 to 3       ",
			"move 1 from 6 to 3       ",
			"move 7 from 8 to 2       ",
			"move 1 from 6 to 9       ",
			"move 2 from 7 to 2       ",
			"move 1 from 9 to 5       ",
			"move 2 from 8 to 6       ",
			"move 1 from 7 to 5       ",
			"move 1 from 3 to 1       ",
			"move 30 from 5 to 2      ",
			"move 1 from 3 to 4       ",
			"move 2 from 6 to 1       ",
			"move 5 from 3 to 4       ",
			"move 2 from 6 to 5       ",
			"move 5 from 4 to 3       ",
			"move 1 from 3 to 1       ",
			"move 4 from 1 to 6       ",
			"move 1 from 2 to 5       ",
			"move 2 from 4 to 9       ",
			"move 4 from 3 to 5       ",
			"move 1 from 3 to 5       ",
			"move 1 from 5 to 3       ",
			"move 6 from 5 to 1       ",
			"move 2 from 1 to 9       ",
			"move 4 from 6 to 2       ",
			"move 1 from 3 to 5       ",
			"move 1 from 5 to 2       ",
			"move 1 from 5 to 2       ",
			"move 8 from 2 to 5       ",
			"move 4 from 9 to 6       ",
			"move 3 from 1 to 4       ",
			"move 3 from 6 to 2       ",
			"move 2 from 4 to 2       ",
			"move 1 from 6 to 1       ",
			"move 1 from 4 to 6       ",
			"move 2 from 5 to 1       ",
			"move 1 from 6 to 8       ",
			"move 3 from 5 to 2       ",
			"move 2 from 5 to 6       ",
			"move 1 from 6 to 7       ",
			"move 1 from 5 to 9       ",
			"move 1 from 7 to 5       ",
			"move 3 from 1 to 9       ",
			"move 3 from 9 to 5       ",
			"move 31 from 2 to 6      ",
			"move 1 from 1 to 3       ",
			"move 1 from 8 to 9       ",
			"move 30 from 6 to 9      ",
			"move 2 from 9 to 8       ",
			"move 13 from 2 to 3      ",
			"move 4 from 5 to 2       ",
			"move 1 from 8 to 4       ",
			"move 1 from 4 to 1       ",
			"move 1 from 1 to 6       ",
			"move 5 from 2 to 8       ",
			"move 1 from 2 to 8       ",
			"move 26 from 9 to 3      ",
			"move 18 from 3 to 8      ",
			"move 1 from 2 to 1       ",
			"move 12 from 3 to 8      ",
			"move 1 from 2 to 3       ",
			"move 3 from 6 to 4       ",
			"move 1 from 1 to 9       ",
			"move 11 from 8 to 5      ",
			"move 1 from 4 to 7       ",
			"move 9 from 3 to 9       ",
			"move 1 from 7 to 8       ",
			"move 11 from 8 to 3      ",
			"move 11 from 3 to 2      ",
			"move 11 from 2 to 9      ",
			"move 19 from 9 to 8      ",
			"move 3 from 5 to 7       ",
			"move 2 from 4 to 2       ",
			"move 2 from 2 to 8       ",
			"move 29 from 8 to 2      ",
			"move 5 from 5 to 4       ",
			"move 1 from 9 to 6       ",
			"move 2 from 5 to 9       ",
			"move 1 from 6 to 9       ",
			"move 7 from 8 to 7       ",
			"move 1 from 9 to 7       ",
			"move 6 from 9 to 1       ",
			"move 1 from 9 to 4       ",
			"move 1 from 5 to 4       ",
			"move 15 from 2 to 5      ",
			"move 3 from 1 to 7       ",
			"move 5 from 5 to 2       ",
			"move 1 from 8 to 3       ",
			"move 1 from 5 to 8       ",
			"move 2 from 3 to 6       ",
			"move 1 from 3 to 8       ",
			"move 9 from 2 to 1       ",
			"move 1 from 8 to 7       ",
			"move 1 from 8 to 3       ",
			"move 10 from 7 to 8      ",
			"move 4 from 7 to 3       ",
			"move 1 from 7 to 2       ",
			"move 1 from 8 to 6       ",
			"move 3 from 6 to 5       ",
			"move 6 from 5 to 8       ",
			"move 3 from 1 to 3       ",
			"move 8 from 3 to 7       ",
			"move 3 from 1 to 3       ",
			"move 4 from 8 to 3       ",
			"move 1 from 4 to 5       ",
			"move 4 from 1 to 4       ",
			"move 1 from 4 to 5       ",
			"move 1 from 7 to 4       ",
			"move 4 from 4 to 1       ",
			"move 2 from 8 to 7       ",
			"move 6 from 5 to 2       ",
			"move 2 from 8 to 1       ",
			"move 6 from 4 to 7       ",
			"move 1 from 5 to 4       ",
			"move 5 from 8 to 6       ",
			"move 1 from 6 to 9       "
	};
}
